name: app_preference_secure_storage
description: secure storage adapter for app_preference
version: 0.1.1
homepage: https://github.com/timnew/app_preference

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  app_preference: ^0.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
