// Mocks generated by Mockito 5.4.2 from annotations
// in app_preference/test/lib/app_preference_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_preference/src/contract.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppPreferenceAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppPreferenceAdapter extends _i1.Mock
    implements _i2.AppPreferenceAdapter {
  @override
  _i3.FutureOr<T?> read<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as _i3.FutureOr<T?>);
  @override
  _i3.FutureOr<void> write<T>(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i3.FutureOr<void>);
  @override
  _i3.FutureOr<String?> serializerRead(String? key) => (super.noSuchMethod(
        Invocation.method(
          #serializerRead,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as _i3.FutureOr<String?>);
  @override
  _i3.FutureOr<void> serializerWrite(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #serializerWrite,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i3.FutureOr<void>);
}
