name: app_preference_shared_preferences
description: shared preferences adapter for app_preference
version: 0.1.0
homepage: https://github.com/timnew/app_preference

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  app_preference:
    path: ../app_preference # TODO: change this to public one
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
