name: app_preference
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/timnew/app_preference

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  mobx: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
